###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: stack-web-development-with-angular-6-and-laravel-5-memcached

    mysql:
      image: mysql:5.7
      container_name: stack-web-development-with-angular-6-and-laravel-5-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=laravel-angular-book
        - MYSQL_USER=laravel-angular-book
        - MYSQL_PASSWORD=123456
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: stack-web-development-with-angular-6-and-laravel-5-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: phpdocker/php-fpm        
      container_name: stack-web-development-with-angular-6-and-laravel-5-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

